#!/usr/bin/env python3
"""
macro.py — Macro Environment Scanner
Pulls market regime data: VIX, rates, S&P, dollar, sector rotation

Usage: python3 scripts/macro.py
Output: data/MACRO_data.md
"""

import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime
import os
import warnings
warnings.filterwarnings('ignore')


SECTORS = {
    'XLK':  'Technology',
    'XLC':  'Comm Services',
    'XLY':  'Consumer Disc',
    'XLF':  'Financials',
    'XLV':  'Healthcare',
    'XLI':  'Industrials',
    'XLP':  'Consumer Staples',
    'XLE':  'Energy',
    'XLB':  'Materials',
    'XLRE': 'Real Estate',
    'XLU':  'Utilities',
}


def safe_get(ticker_symbol, period='3mo'):
    try:
        t = yf.Ticker(ticker_symbol)
        hist = t.history(period=period)
        if hist.empty:
            return None
        return hist
    except Exception:
        return None


def pct_change_period(hist, days):
    if hist is None or len(hist) < days:
        return None
    try:
        return ((hist['Close'].iloc[-1] - hist['Close'].iloc[-days]) / hist['Close'].iloc[-days]) * 100
    except Exception:
        return None


def latest_close(hist):
    if hist is None or hist.empty:
        return None
    return hist['Close'].iloc[-1]


def run_macro_scan():
    now = datetime.now().strftime('%Y-%m-%d %H:%M')
    print("\n🌍 Running macro scan...")

    lines = []
    lines.append(f"# MACRO ENVIRONMENT — {now}")
    lines.append(f"*Auto-generated by macro.py | Source: Yahoo Finance*\n")
    lines.append("---")

    # ── VIX ──
    print("  → VIX (fear gauge)...")
    vix_hist = safe_get('^VIX', period='1mo')
    vix = latest_close(vix_hist)
    if vix:
        if vix < 15:
            vix_regime = "🟢 COMPLACENT — Market very calm, low fear"
            vix_signal = "Risk-On"
        elif vix < 20:
            vix_regime = "🟢 CALM — Normal conditions"
            vix_signal = "Risk-On"
        elif vix < 25:
            vix_regime = "🟡 ELEVATED — Some nervousness"
            vix_signal = "Neutral"
        elif vix < 35:
            vix_regime = "🔴 FEAR — Market stressed"
            vix_signal = "Risk-Off"
        else:
            vix_regime = "🔴 PANIC — Extreme fear, potential capitulation"
            vix_signal = "Risk-Off / Contrarian Buy"
        vix_1m = pct_change_period(vix_hist, min(20, len(vix_hist)-1))
        vix_trend = f"{'↑ Rising' if vix_1m and vix_1m > 5 else '↓ Falling' if vix_1m and vix_1m < -5 else '→ Stable'}"
    else:
        vix_regime = "N/A"
        vix_signal = "N/A"
        vix_trend = "N/A"

    lines.append("\n## 😰 FEAR GAUGE (VIX)")
    lines.append(f"- **VIX Level:** {vix:.1f}" if vix else "- **VIX Level:** N/A")
    lines.append(f"- **Regime:** {vix_regime}")
    lines.append(f"- **Trend:** {vix_trend}")
    lines.append(f"- **Signal:** {vix_signal}")

    # ── 10Y YIELD ──
    print("  → 10Y yield (rates)...")
    tnx_hist = safe_get('^TNX', period='3mo')
    tnx = latest_close(tnx_hist)
    tnx_3m = pct_change_period(tnx_hist, min(60, len(tnx_hist)-1)) if tnx_hist is not None else None
    if tnx:
        if tnx < 3.5:
            rate_regime = "🟢 LOW — Favorable for growth stocks"
        elif tnx < 4.5:
            rate_regime = "🟡 MODERATE — Neutral for equities"
        elif tnx < 5.5:
            rate_regime = "🔴 HIGH — Headwind for high-multiple stocks"
        else:
            rate_regime = "🔴 VERY HIGH — Significant valuation pressure"
        rate_trend = "Rising 📈" if tnx_3m and tnx_3m > 5 else "Falling 📉" if tnx_3m and tnx_3m < -5 else "Stable →"
    else:
        rate_regime = "N/A"
        rate_trend = "N/A"

    lines.append("\n## 📈 RATES (10Y Treasury Yield)")
    lines.append(f"- **10Y Yield:** {tnx:.2f}%" if tnx else "- **10Y Yield:** N/A")
    lines.append(f"- **Regime:** {rate_regime}")
    lines.append(f"- **3M Trend:** {rate_trend}")

    # ── S&P 500 ──
    print("  → S&P 500 performance...")
    spy_hist = safe_get('SPY', period='1y')
    spy_price = latest_close(spy_hist)
    spy_1m  = pct_change_period(spy_hist, 21)
    spy_3m  = pct_change_period(spy_hist, 63)
    spy_6m  = pct_change_period(spy_hist, 126)
    spy_1y  = pct_change_period(spy_hist, 252)

    # Is S&P above its 200MA?
    spy_200ma_signal = "N/A"
    if spy_hist is not None and len(spy_hist) >= 200:
        sma200 = spy_hist['Close'].rolling(200).mean().iloc[-1]
        spy_200ma_signal = "🟢 Above 200MA — Bull market" if spy_price > sma200 else "🔴 Below 200MA — Bear territory"

    lines.append("\n## 📊 MARKET (S&P 500 / SPY)")
    lines.append(f"- **SPY Price:** ${spy_price:.2f}" if spy_price else "- **SPY Price:** N/A")
    lines.append(f"- **1M:** {spy_1m:+.1f}%" if spy_1m else "- **1M:** N/A")
    lines.append(f"- **3M:** {spy_3m:+.1f}%" if spy_3m else "- **3M:** N/A")
    lines.append(f"- **6M:** {spy_6m:+.1f}%" if spy_6m else "- **6M:** N/A")
    lines.append(f"- **1Y:** {spy_1y:+.1f}%" if spy_1y else "- **1Y:** N/A")
    lines.append(f"- **Trend:** {spy_200ma_signal}")

    # ── DOLLAR INDEX ──
    print("  → Dollar strength...")
    dxy_hist = safe_get('DX-Y.NYB', period='3mo')
    dxy = latest_close(dxy_hist)
    dxy_3m = pct_change_period(dxy_hist, min(60, len(dxy_hist)-1)) if dxy_hist is not None else None
    if dxy:
        dxy_signal = "Strong $ — headwind for multinationals" if dxy_3m and dxy_3m > 3 else \
                     "Weak $ — tailwind for multinationals" if dxy_3m and dxy_3m < -3 else \
                     "Stable $"

    lines.append("\n## 💵 US DOLLAR (DXY)")
    lines.append(f"- **DXY Level:** {dxy:.1f}" if dxy else "- **DXY Level:** N/A")
    lines.append(f"- **3M Change:** {dxy_3m:+.1f}%" if dxy_3m else "- **3M Change:** N/A")
    lines.append(f"- **Signal:** {dxy_signal}" if dxy else "- **Signal:** N/A")

    # ── GROWTH vs VALUE ──
    print("  → Growth vs value (QQQ/IWD)...")
    qqq_hist = safe_get('QQQ', period='3mo')
    iwd_hist = safe_get('IWD', period='3mo')
    qqq_3m = pct_change_period(qqq_hist, min(60, len(qqq_hist)-1)) if qqq_hist is not None else None
    iwd_3m = pct_change_period(iwd_hist, min(60, len(iwd_hist)-1)) if iwd_hist is not None else None

    if qqq_3m is not None and iwd_3m is not None:
        spread = qqq_3m - iwd_3m
        rotation = "🟢 GROWTH outperforming — momentum in tech/AI names" if spread > 3 else \
                   "🔴 VALUE outperforming — defensive rotation, risk-off" if spread < -3 else \
                   "🟡 NEUTRAL — no clear rotation signal"
    else:
        rotation = "N/A"

    lines.append("\n## 🔄 GROWTH vs VALUE ROTATION")
    lines.append(f"- **QQQ 3M:** {qqq_3m:+.1f}%" if qqq_3m else "- **QQQ 3M:** N/A")
    lines.append(f"- **IWD 3M:** {iwd_3m:+.1f}%" if iwd_3m else "- **IWD 3M:** N/A")
    lines.append(f"- **Rotation Signal:** {rotation}")

    # ── SECTOR PERFORMANCE ──
    print("  → Sector rotation...")
    lines.append("\n## 🏭 SECTOR ROTATION (1M Performance)")
    lines.append("| Sector | ETF | 1M Return | 3M Return | Signal |")
    lines.append("|---|---|---|---|---|")

    sector_data = []
    for etf, name in SECTORS.items():
        hist = safe_get(etf, period='3mo')
        r1m = pct_change_period(hist, 21)
        r3m = pct_change_period(hist, min(60, len(hist)-1)) if hist is not None else None
        sector_data.append((etf, name, r1m, r3m))

    # Sort by 1M return
    sector_data.sort(key=lambda x: x[2] if x[2] is not None else -999, reverse=True)

    for etf, name, r1m, r3m in sector_data:
        signal = "🟢 HOT" if r1m and r1m > 5 else "🔴 COLD" if r1m and r1m < -3 else "🟡 Neutral"
        r1m_str = f"{r1m:+.1f}%" if r1m is not None else "N/A"
        r3m_str = f"{r3m:+.1f}%" if r3m is not None else "N/A"
        lines.append(f"| {name} | {etf} | {r1m_str} | {r3m_str} | {signal} |")

    # ── MACRO VERDICT ──
    print("  → Building macro verdict...")

    # Determine overall regime
    risk_signals = []
    if vix and vix < 20: risk_signals.append("risk-on")
    elif vix and vix > 25: risk_signals.append("risk-off")
    if spy_1m and spy_1m > 2: risk_signals.append("risk-on")
    elif spy_1m and spy_1m < -3: risk_signals.append("risk-off")
    if qqq_3m and iwd_3m and (qqq_3m - iwd_3m) > 3: risk_signals.append("risk-on")
    elif qqq_3m and iwd_3m and (qqq_3m - iwd_3m) < -3: risk_signals.append("risk-off")

    risk_on_count = risk_signals.count("risk-on")
    risk_off_count = risk_signals.count("risk-off")

    if risk_on_count > risk_off_count:
        overall_regime = "🟢 RISK-ON — Favorable for growth and AI names"
        regime_action = "Lean into high-quality growth. Momentum strategies working."
    elif risk_off_count > risk_on_count:
        overall_regime = "🔴 RISK-OFF — Defensive posture recommended"
        regime_action = "Reduce size on high-beta names. Quality and cash flow matter more."
    else:
        overall_regime = "🟡 MIXED — No clear directional signal"
        regime_action = "Stock-picking market. Focus on individual catalysts over macro bets."

    if tnx and tnx > 4.5:
        rate_note = f"⚠️  Rates elevated at {tnx:.2f}% — high-multiple stocks face valuation headwind"
    elif tnx and tnx < 4.0:
        rate_note = f"✅ Rates supportive at {tnx:.2f}% — growth stock valuations more defensible"
    else:
        rate_note = f"→ Rates neutral at {tnx:.2f}%" if tnx else "→ Rate data unavailable"

    lines.append("\n---\n## 🎯 MACRO VERDICT")
    lines.append(f"- **Overall Regime:** {overall_regime}")
    lines.append(f"- **Action:** {regime_action}")
    lines.append(f"- **Rate Context:** {rate_note}")
    lines.append(f"- **VIX Context:** {vix_signal} — {vix_regime}")

    lines.append(f"\n*Macro scan completed: {now}*")

    return "\n".join(lines)


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.join(script_dir, '..', 'data')
    os.makedirs(data_dir, exist_ok=True)
    output_file = os.path.join(data_dir, 'MACRO_data.md')

    output = run_macro_scan()

    with open(output_file, 'w') as f:
        f.write(output)

    print(f"\n✅ Macro data saved to: data/MACRO_data.md")
    print(f"   Open Claude Code and type: /stock-analyzer → .macro")


if __name__ == '__main__':
    main()
